\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename simplemagic.info
@settitle SimpleMagic Documentation
@headings double
@c %**end of header

@c ----------------------------------------------------------------
@set simplemetrics_version 0.1
@set simplemetrics_year 2015
@set simplemetrics_date November @value{simplemetrics_year}
@set package SimpleMetrics
@c ----------------------------------------------------------------

@titlepage
@headings off
@title SimpleMetrics Package
@subtitle Version @value{simplemetrics_version}
@subtitle @value{simplemetrics_date}
@author Gray Watson

@page
This manual is licensed by Gray Watson under the Creative Commons Attribution-Share Alike 3.0 License.

Permission is granted to make and distribute verbatim copies of this manual provided this license
notice and this permission notice are preserved on all copies.
@end titlepage

@c ----------------------------------------------------------------

@c In the printed manual, we put the contents at the front.  For the digital manuals it is at the end. 
@iftex
@contents
@end iftex

@c ----------------------------------------------------------------
@node Top, Quick Start, (dir), (dir)
@top SimpleMetrics
@everyheading @thischapter @| @thispage @| @today{}

Version @value{simplemetrics_version} -- @value{simplemetrics_date}

@cindex introduction
@cindex author
@cindex simple metrics
This package provides some simple metrics features that allow for the simple recording on application metrics and publishing them to
various different local or cloud storage and cloud metric systems.  You code can register a metric and then not worry about how it
is published or persisted.

To get started quickly using SimpleMetrics, @pxref{Quick Start}.
@ifhtml
There is also a @uref{http://256.com/sources/simplemetrics/docs/simplemetrics.pdf, PDF version of this documentation}.
@end ifhtml
@iftex
There is also a @uref{http://256.com/sources/simplemetrics/docs/simplemetrics.html, HTML version of this documentation}.
@end iftex

Gray Watson @uref{http://256.com/gray/}

@menu
* Quick Start::                Start using SimpleMetrics quickly.
* Using::                      How to use SimpleMetrics.
* License::                    Open Source license for the project.
* Index of Concepts::          Index of concepts in the manual.
@end menu

@c ----------------------------------------------------------------
@node Quick Start, Using, Top, Top
@chapter Start Using Quickly

@cindex getting started
@cindex how to get started
@cindex quick start
To use SimpleMetrics you need to do the following steps.  For more information, @pxref{Using}.

@enumerate

@item Download SimpleMetrics from the @uref{http://256.com/sources/simplemetrics/releases/, SimpleMetrics release page}.
@xref{Downloading}.

@item Create an instance of the @code{MetricsManager} class which manages the metrics in our application.

@example
MetricsManager metricsManager = new MetricsManager();
@end example

@item Create a persister such as the @code{LoggingMetricsPersister} which logs the metrics and values to
@code{java.util.Logger}.

@example
LoggingMetricsPersister persister =
   new LoggingMetricsPersister();
metricsManager.registerMetric(hitCounter);
@end example

@item Create at least one metrics which monitors an application value and register them with the manager.

@example
ControlledMetricAccum hitCounter =
   new ControlledMetricAccum("example", null, "hits",
      "number of hits to the cache", null);
metricsManager.registerMetric(hitCounter);
@end example

@item Possible use the @code{MetricsPersisterJob} which starts a background thread to call @code{persist()} on
the @code{MetricsManager} every so often automatically.

@example
MetricsPersisterJob persisterThread =
   new MetricsPersisterJob(manager, 1000, 1000, true);
@end example

@end enumerate

For somewhat more extensive instructions, @pxref{Using}.

@c ----------------------------------------------------------------
@node Using, Downloading, Quick Start, Top
@chapter Using SimpleMetrics

@cindex how to use
@cindex using SimpleMetrics
@menu
* Downloading ::                  Downloading the SimpleMetrics jar.
* Creating a MetricsManager ::    Creating a MetricsManager instance.
* Using Metrics Persisters ::     Using or creating a metrics persister.
* Registering Metrics ::          Creating and registering metrics.
* Using MetricsUpdater ::         Using the MetricsUpdate interface.
* Maven ::                        How to use with Maven.
@end menu

@c ----------------------------------------------------------------
@node Downloading, Creating a MetricsManager, Using, Using
@section Downloading Jar

@cindex how to download the jars
@cindex downloading the jars
@cindex where to get new jars
To get started with SimpleMetrics, you will need to download the jar file.  The @uref{http://256.com/sources/simplemetrics/releases/, SimpleMetrics
release page} is the default repository but the jars are also available from the @uref{http://repo1.maven.org/maven2/com/j256/simplemetrics/,
central maven repository}.

The code works with Java 6 or later.

@c ----------------------------------------------------------------
@node Creating a MetricsManager, Using Metrics Persisters, Downloading, Using
@section Creating a MetricsManager Instance

@cindex MetricsManager
@cindex managing the metrics
The @code{MetricsManager} is the class which manages the metrics in the application, updates the values of the metrics
when necessary, and persisting the metrics to disk or network when requests.

@cindex loading metrics entries
@cindex metrics files
The metrics entries are relatively complex but in general look something like the following.  The configuration line says to
look at the start of the file for the string @code{"GIF8"}.  If it is there then the file is "GIF image data".

@cindex sample metrics definition
@example
0       string          GIF8            GIF image data
@end example

@cindex alternative metrics files
@cindex /etc/metrics
If you do not want to use the internal metrics definitions, you can also construct the @code{ContentInfoUtil} class with a file
or directory to have it parse and use another definition file.

@example
ContentInfoUtil util = new ContentInfoUtil("/etc/metrics");
@end example

@emph{WARNING:} although we've tried to support different types of metrics entries, there are local per-OS variations that may
not be supported.  

@c ----------------------------------------------------------------
@node Finding Content Info, Content Info, Downloading, Using
@section How To Find The Content Info

Once you have loaded the metrics entry information into your @code{ContentInfoUtil}, you can use the utility class to find
the content info of files, byte arrays, or @code{InputStream}s.  The base method gets content info information from a
@code{byte[]}.

@cindex byte array content
@example
byte[] uploadedBytes = ...;
ContentInfo info = util.findMatch(uploadedBytes);
@end example

You can also get the content type of a file which is read with a @code{FileInputStream}:

@cindex file content
@example
ContentInfo info = util.findMatch("/tmp/uploadedFile.tmp");
// File uploadedFile = ...
// ContentInfo info = util.findMatch(uploadedFile);
@end example

@cindex input stream content
If you have an @code{InputStream}, you can also use it directly:

@example
InputStream inputStream = ...
ContentInfo info = util.findMatch(inputStream);
@end example

@cindex ContentInfoInputStreamWrapper
@cindex wrapped input stream
@cindex delegate to input stream
@cindex input stream wrapper
If you want to process a stream of bytes as the bytes are being read, you can use the @code{ContentInfoInputStreamWrapper}
utility class.  This takes an @code{InputStream} which it wraps and delegates to.  After you have read the bytes through
the wrapper, you can call the @code{findMatch()} method to get its content information.

@example
HttpServletRequest request = ...
ContentInfoInputStreamWrapper inputStream
   = new ContentInfoInputStreamWrapper(request.getInputStream());
// read in the file from the http request, ...
// after we have read it in, we can get its content-info 
ContentInfo info = inputStream.findMatch();
@end example

For the file and stream versions, the first 10 kilobytes of the data is read and processed.

There is also a long internal list of file types copied from the Apache list --
@uref{http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types?view=co}.  Not all of the files in this list
have associated metrics number information.  However, with the list you can look up mime-types or by file-extension and
get the associated information. 

@cindex file extensions
@cindex extensions
You can use the internal list to lookup by file-extension:

@example
// find details about files with .pdf extension
ContentInfo info =
   ContentInfoUtil.findExtensionMatch("file.pdf");
// you can even just pass in the extension name
ContentInfo info =
   ContentInfoUtil.findExtensionMatch("DOC");
@end example

@cindex mime-type
Or you can look up by mime-type:

@example
// find details about this mime-type
ContentInfo info =
   ContentInfoUtil.findMimeTypeMatch("image/vnd.dwg");
@end example

Some internal entries provide more information than others.  This list is a work in progress.  Please submit improvements
and edits as necessary.

@c ----------------------------------------------------------------
@node Content Info, License, Finding Content Info, Using
@section Content Information

If the @code{findMatch(...)} method does not recognize the content then it will return null.  If it does match one of the
entries then it will return a @code{ContentInfo} class which provides:

@itemize @bullet
@item Enumerated content-type if the type is common otherwise set to @code{OTHER}.  This is determined by mapping the
mime-type string to an internal enumerated type and is not determined from the metrics file entries.
@item Approximate content-name.  If the content-type is known then this will be a constant string.  If not know then this
is usually the first word of the full message from the metrics file. 
@item Details about the content produced by the metrics file.
@cindex mime-type
@item Mime-type string if one configured by the config file.
@cindex file extensions
@cindex extensions
@item Associated file-extensions if in the internal list.
@end itemize

Here are some examples of @code{ContentInfo} output:

@itemize @bullet
@item html, mime 'text/html', msg 'HTML document text'
@item java, msg 'Java serialization data, version 5'
@item pdf, mime 'application/pdf', msg 'PDF document, version 1.4'
@item gzip, mime 'application/x-gzip', msg 'gzip compressed data, was "", from Unix...'
@item gif, mime 'image/gif', msg 'GIF image data, version 89a, 16 x 16'
@item png, mime 'image/png', msg 'PNG image, 600 x 371, 8-bit/color RGB, non-interlaced'
@item mp4a, mime 'audio/mp4', msg 'ISO Media, MPEG v4 system, iTunes AAC-LC'
@item word, mime 'application/msword', msg 'Microsoft Word Document'
@item wav, mime 'audio/x-wav', msg 'RIFF (little-endian) data, WAVE audio...'
@item jpeg, mime 'image/jpeg', msg 'JPEG image data, JFIF standard 1.01'
@end itemize

@c ----------------------------------------------------------------
@node Maven, License, Content Info, Using
@section Using With Maven

@cindex Maven, use with
@cindex pom.xml dependency
To use SimpleMetrics with maven, include the following dependency in your @file{pom.xml} file:

@example
<dependency>
	<groupId>com.j256.simplemetrics</groupId>
	<artifactId>simplemetrics</artifactId>
	<version>@value{simplemetrics_version}</version>
</dependency>
@end example 

@c ----------------------------------------------------------------
@node License, Index of Concepts, Maven, Top
@chapter Open Source License

@cindex license
@cindex open source license
This document is part of the SimpleMetrics project.

Permission to use, copy, modify, and/or distribute this software for any purpose with or without fee is hereby
granted, provided that this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING
ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL,
DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE
USE OR PERFORMANCE OF THIS SOFTWARE.

The author may be contacted via @uref{http://256.com/sources/simplemetrics/}

@c ----------------------------------------------------------------
@node Index of Concepts,, License, Top
@unnumbered Index of Concepts

@printindex cp

@ifhtml
@contents
@end ifhtml

@bye
